### ISSUE TITLE
Upgrade Angular and SDK

### ISSUE THREAD

**Issue by ntaoo** [ntaoo/material2_dart#36]
- [x] Rewrite test code with beta.21 testing API.

- [x] Add some linters for even stronger type checks.

**Comment by zoechi** [comment]
if you don't have settings prepared, you can use

```yml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
#    - '**/**.g.dart'
linter:
  rules:
# Error Rules
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps

# Style Rules
    - always_declare_return_types
#    - always_specify_types
    - annotate_overrides
#    - avoid_as
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
#    - public_member_api_docs
    - slash_for_doc_comments
#    - sort_constructor_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters

# Pub Rules
    - package_names
```
